platform :ios, '9.0'

source 'https://github.com/kantarsifo/kantar-sifo-mobile-analytics-podspec.git'

target 'TSMobileAnalyticsIntegration' do

  use_frameworks!

  pod 'TSMobileAnalytics'

  target 'TSMobileTaggingHybridIntegration' do
    inherit! :search_paths
  end

  target 'TSMobileAnalyticsIntegrationTests' do
    inherit! :search_paths
  end

  target 'TSMobileTaggingHybridIntegrationTests' do
    inherit! :search_paths
  end

end
