platform :ios, '9.0'

source 'https://github.com/kantarsifo/kantar-sifo-mobile-analytics-podspec.git'

target 'NativeIntegration' do
  use_frameworks!
  pod 'TSMobileAnalytics'
end

target 'HybridIntegration' do
  use_frameworks!
  pod 'TSMobileAnalytics'
end
